// <auto-generated />
using System;
using ADBee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ADBee.Migrations
{
    [DbContext(typeof(ADSystemDbContext))]
    [Migration("20200504010736_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ADBee.Models.AdStastic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad_Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Click_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip4Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ip4_1")
                        .HasColumnType("int");

                    b.Property<int>("Ip4_2")
                        .HasColumnType("int");

                    b.Property<int>("Ip4_3")
                        .HasColumnType("int");

                    b.Property<int>("Ip4_4")
                        .HasColumnType("int");

                    b.Property<string>("Ip6Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStartedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdStastics");
                });

            modelBuilder.Entity("ADBee.Models.Advertisement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad_Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PublishUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
